### ISSUE TITLE
Why 'PREMARSHALLING-ASTAR-2015' has been removed ?

### ISSUE THREAD

**Issue by lteu** [coseal/aslib_data#22]
Hi All,

I would like to know why the scenario 'PREMARSHALLING-ASTAR-2015' of ICON-challenge 
has been removed. 

Tks

**Comment by mlindauer** [comment]
Hi,

Please see release notes for ASlib 3.0.
'PREMARSHALLING-ASTAR-2015' was renamed to 'CPMP-2015'. 

Cheers,
Marius
