### ISSUE TITLE
OpenML_MetaLearning_2016 has missing values

### ISSUE THREAD

**Issue by mlindauer** [coseal/aslib_data#9]
Hi,

I wanted to have look at the OpenML_MetaLearning_2016 scenario. Unfortunately, I think there was a misunderstanding at the PR: We have missing values in algorithm_runs.arff now -- Not encoded as ?, but simply missing lines. For example, the combination of instance `1073` and algorithm `523` is missing. 
We could fix this by simply adding the worst possible performance for all these missing values and mark them as crashes.

What do you think?

Cheers,
Marius

**Comment by larskotthoff** [comment]
Could we check things like that in the python checker please? Or did I miss something in the output?

**Comment by mlindauer** [comment]
It is checking for `?` but not for missing lines. 
Let us talk about the future of the ASlib eco system (including the python checker) next week at the Dagstuhl. I would like to talk with you anyway.

For the moment, how do we fix the scenario?

**Comment by WilliamRaynaut** [comment]
Hello,

Those missing lines comes from the fact that one or more evaluation criterion was not computed on this run (for unknown reasons, since this is not factored in openML). So it does not necessarily means the run has failed. 
However tagging it has failed it is probably the only practical solution to make them appear without missing values...

Cheers,
William

**Comment by mlindauer** [comment]
Hi,

I talked with Jan von Rijn (since he is now a member of our ML4AAD group). 
Indeed, OpenML does not run every algorithm on every data set. It has to be done by the users. So, if we flag this runs with poor performance, it would be strongly misleading.

Furthermore, maybe even more important, we should not use `algorithms` and `datasets` id to extract data from OpenML; but we should use `tasks` (to ensure the same splits, goal etc) and `setups` (to ensure the same setup of the algorithms, including hyperparameter settings). 
@WilliamRaynaut: have you used algorithms and datasets, or tasks and setups?

Last but not least, here is a list of tasks and setup from which we could extract a full matrix:

```
Tasks: {1701, 1702, 1705, 1710, 1711, 1713, 1714, 1715, 1717, 1719, 1720, 1721, 1722, 1723, 1727, 1728, 1730, 1731, 1735, 1736, 1740, 1742, 1744, 1752, 1757, 1764, 2097, 2098, 2102, 7532, 7535, 7536, 10041, 10045, 10046, 10047, 10050, 10053, 10054, 10055, 10067, 10069, 10070, 10071, 10072, 10074, 10075, 10076, 10077, 10079, 10080, 10082, 10083, 10084, 10085, 10086, 125849, 125850, 125851, 125852, 125853, 125854, 125855, 125857, 125859, 125861, 125865, 125866, 125867, 125868, 125869, 125870, 125871, 125873, 125874, 125875, 125876, 125877, 125878, 125879, 125880, 125881, 125884, 125885, 125886, 125887, 125888, 125889, 125890, 125891, 125892, 125894, 125897, 125898, 125899, 125901, 125902, 125905, 125906, 125909, 125910, 125911, 125913, 125914, 125915};
Setups: {2361, 2362, 2364, 2367, 2368, 2369, 2370, 2371, 2373, 2381, 2647, 2869, 2882, 2889, 2891, 2893, 2894, 2897, 2898, 2900, 2903, 2904, 2906, 6250, 6352, 6355, 6378, 8990, 8994, 8995}; 
```

Best,
Marius

**Comment by WilliamRaynaut** [comment]
The key used were Dataset.did and Implementation.id, which indeed does not ensure task and setup identity. We could not at the time produce a full matrix of significant size of tasks and setups, and it seems from the list you posted, that it has not changed much.

I currently have a piece of working code to automate weka experiment from task ids and setup ids, so I could probably expand this matrix a bit, but only for weka setups...
Also, how did you get these lists ? To build mine I had to go through complete biclique extraction, which was quite time consuming...

**Comment by mlindauer** [comment]
> Also, how did you get these lists ?

I asked Jan :-)
He used this list for his phd thesis.

**Comment by mlindauer** [comment]
How to proceed with this scenario? 
Imho, @WilliamRaynaut has gathered the data based on `algorithms` and `datasets`, and not on `tasks` and `setups`, the scenario is not valid.

**Comment by larskotthoff** [comment]
Let's drop it then.

**Comment by mlindauer** [comment]
dropped and closed
